### PR TITLE
[4946][ADD] mail_show_follower

### PR DESCRIPTION
**Pull request by nobuQuartile**
[4946](https://www.quartile.co/web?db=qrtl&token=z9OpY14OSBGGYn2qv0Ha#id=4946&menu_id=505&cids=3&action=1457&model=project.task&view_type=form)

### CODE REVIEW

**Comment by yostashiro** [comment]
Superseding #28

**Comment by nobuQuartile** [comment]
I finished fixing the module.

**Review by yostashiro — COMMENTED** [review]
@nobuQuartile I find it hard to capture the context from the current commit message. Can you update the commit message as follows if you are OK with it?

```
[FIX] mail_show_follower: Company identification in _send()

Before this commit, 'Show Internal Users CC' would always be False,
regardless of the setting in the company, in case the message came
from a record with a company_id field but without a value assignment to
it (e.g., a partner record with no company), as company would be an
empty record.

This commit fixes the behavior by capturing company from self.env in
these cases.
```

**Comment by nobuQuartile** [comment]
@yostashiro 
OK. It is easier to understand than mine. Thanks you.
But, I think we have to make another commit message for OCA because [a commit message should not be longer than 50 characters: This is a commit message](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message)
I will make it.

**Comment by yostashiro** [comment]
> But, I think we have to make another commit message for OCA because [a commit message should not be longer than 50 characters: This is a commit message](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message)

That is only for the summary line, and it's just a guideline. My suggestion will probably be accepted with no objection.

**Comment by nobuQuartile** [comment]
I see. I will enter the same message at OCA commit.

**Comment by nobuQuartile** [comment]
I did force push & change the commit message.

**Review by yostashiro — APPROVED** [review]

**Pull request merged**
